name: "CI"

env:
  HARDHAT_PROFILE: "ci"
  SEPOLIA_RPC_URL: "https://eth-sepolia.g.alchemy.com/v2/JehibbYhz7RXwY9jhJ8pG" # Lưu Alchemy API key trong GitHub Secrets

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "20" 

      - name: "Install pnpm"
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: "Install the Node.js dependencies"
        run: "pnpm install --frozen-lockfile"

      - name: "Lint the code"
        run: "pnpm run lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: "Install pnpm"
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: "Install the Node.js dependencies"
        run: "pnpm install --frozen-lockfile"

      - name: "Build the contracts"
        run: "npx hardhat compile"

      - name: "Add build summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    needs: ["lint", "build"]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: "Install pnpm"
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: "Install the Node.js dependencies"
        run: "pnpm install --frozen-lockfile"

      - name: "Show the Hardhat config"
        run: "npx hardhat config"

      - name: "Run the tests"
        env:
          ALCHEMY_API_KEY: "${{ secrets.ALCHEMY_API_KEY }}"
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
        run: "npx hardhat test"

      - name: "Add test summary"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  deploy-sepolia:
    needs: ["test"]
    runs-on: "ubuntu-latest"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: "Install pnpm"
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: "Install the Node.js dependencies"
        run: "pnpm install --frozen-lockfile"

      - name: "Deploy to Sepolia"
        env:
          ALCHEMY_API_KEY: "${{ secrets.ALCHEMY_API_KEY }}"
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
          ETHERSCAN_API_KEY: "${{ secrets.ETHERSCAN_API_KEY }}"
        run: "npx hardhat run scripts/deploy.js --network sepolia"

      - name: "Verify contracts on Etherscan"
        env:
          ETHERSCAN_API_KEY: "${{ secrets.ETHERSCAN_API_KEY }}"
        run: "npx hardhat verify --network sepolia"

      - name: "Add deploy summary"
        run: |
          echo "## Deploy result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Deployed to Sepolia" >> $GITHUB_STEP_SUMMARY